# Generated by Django 5.0.1 on 2024-03-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profile_pic_url', models.CharField(default='img/default_profile_pic.jpg', max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profile_pic_url', models.CharField(default='img/default_profile_pic.jpg', max_length=2000)),
                ('student_id', models.IntegerField()),
                ('personal_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tutor')),
                ('course', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
