# Generated by Django 5.0.1 on 2024-03-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic_url',
            field=models.CharField(default='main/img/default_profile_pic.jpg', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_pic_url',
            field=models.CharField(default='main/img/default_profile_pic.jpg', max_length=2000),
        ),
    ]
